verdanta_project:
  outputs:
    dev:
      catalog: verdanta_dev
      host: dbc-9dabf5c9-756d.cloud.databricks.com
      http_path: /sql/1.0/warehouses/6b5884a11a6d64b4
      schema: silver
      threads: 1
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
