sources:
  - name: silver
    database: verdanta_dev  
    schema: silver  
    tables:
      - name: customers
      - name: employees
      - name: order_items
      - name: orders
      - name: products
      - name: returns
      - name: stores